development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: seproe_rails4_development
  pool: 5
  username: root
  password:

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: seproe_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: seproe_production
  pool: 5
  username: root
  password: 'Malaa#83'
  socket: /var/run/mysqld/mysqld.sock