development:
  adapter: postgresql
  database: seproe_rails4_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: seproe_rails4_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
